-- ==================================================================================
-- Business Analysis Script: Sales Pipeline & CRM Performance
-- File Name: business_analysis.sql
-- ==================================================================================
USE SalesPerformanceDW;
GO
-- ==================================================================================
-- OBJECTIVE 1: PIPELINE METRICS
-- ==================================================================================

-- 1. Calculate the number of sales opportunities created each month using "engage_date",
-- and identify the month with the most opportunities.
PRINT '--- Objective 1.1: Opportunities Created Each Month ---';
SELECT 
    FORMAT(engage_date, 'yyyy-MM') AS engagement_month,
    COUNT(*) AS opportunities_count
FROM vw_sales_pipeline
WHERE engage_date IS NOT NULL
GROUP BY FORMAT(engage_date, 'yyyy-MM')
ORDER BY engagement_month ASC;

-- Query to isolate the single peak month with the highest velocity
SELECT TOP 1
    FORMAT(engage_date, 'yyyy-MM') AS top_engagement_month,
    COUNT(*) AS opportunities_count
FROM vw_sales_pipeline
WHERE engage_date IS NOT NULL
GROUP BY FORMAT(engage_date, 'yyyy-MM')
ORDER BY opportunities_count DESC;


-- 2. Find the average time deals stayed open (from "engage_date" to "close_date"),
-- and compare closed deals versus won deals.
PRINT '--- Objective 1.2: Average Time Deals Stayed Open (Days) ---';
SELECT 
    deal_stage,
    COUNT(*) AS deal_count,
    AVG(DATEDIFF(day, engage_date, close_date)) AS avg_days_open
FROM vw_sales_pipeline
WHERE engage_date IS NOT NULL AND close_date IS NOT NULL
GROUP BY deal_stage
UNION ALL
SELECT 
    'All Closed Deals (Won & Lost)' AS deal_stage,
    COUNT(*) AS deal_count,
    AVG(DATEDIFF(day, engage_date, close_date)) AS avg_days_open
FROM vw_sales_pipeline
WHERE engage_date IS NOT NULL AND close_date IS NOT NULL AND deal_stage IN ('Won', 'Lost');


-- 3. Calculate the percentage of deals in each stage, and determine what share were lost.
PRINT '--- Objective 1.3: Percentage of Deals in Each Stage ---';
SELECT 
    deal_stage,
    COUNT(*) AS total_deals,
    CAST(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER() AS DECIMAL(5,2)) AS percentage_share
FROM vw_sales_pipeline
GROUP BY deal_stage
ORDER BY percentage_share DESC;


-- 4. Compute the win rate for each product, and identify which one had the highest win rate.
PRINT '--- Objective 1.4: Win Rate by Product ---';
SELECT 
    product,
    COUNT(CASE WHEN deal_stage = 'Won' THEN 1 END) AS won_deals,
    COUNT(CASE WHEN deal_stage IN ('Won', 'Lost') THEN 1 END) AS total_closed_deals,
    CAST(COUNT(CASE WHEN deal_stage = 'Won' THEN 1 END) * 100.0 / 
         NULLIF(COUNT(CASE WHEN deal_stage IN ('Won', 'Lost') THEN 1 END), 0) AS DECIMAL(5,2)) AS win_rate_percentage
FROM vw_sales_pipeline
GROUP BY product
ORDER BY win_rate_percentage DESC;


-- ==================================================================================
-- OBJECTIVE 2: SALES AGENT PERFORMANCE
-- ==================================================================================

-- 1. Calculate the win rate for each sales agent, and find the top performer.
PRINT '--- Objective 2.1: Win Rate by Sales Agent ---';
SELECT 
    sales_agent,
    COUNT(CASE WHEN deal_stage = 'Won' THEN 1 END) AS won_deals,
    COUNT(CASE WHEN deal_stage IN ('Won', 'Lost') THEN 1 END) AS total_closed_deals,
    CAST(COUNT(CASE WHEN deal_stage = 'Won' THEN 1 END) * 100.0 / 
         NULLIF(COUNT(CASE WHEN deal_stage IN ('Won', 'Lost') THEN 1 END), 0) AS DECIMAL(5,2)) AS win_rate_percentage
FROM vw_sales_pipeline
GROUP BY sales_agent
ORDER BY win_rate_percentage DESC;


-- 2. Calculate the total revenue by agent, and see who generated the most.
PRINT '--- Objective 2.2: Total Revenue Generated by Agent ---';
SELECT 
    sales_agent,
    SUM(close_value) AS total_revenue
FROM vw_sales_pipeline
WHERE deal_stage = 'Won'
GROUP BY sales_agent
ORDER BY total_revenue DESC;


-- 3. Calculate win rates by manager to determine which manager’s team performed best.
PRINT '--- Objective 2.3: Win Rates by Manager ---';
SELECT
    st.manager,
    COUNT(CASE WHEN sp.deal_stage = 'Won' THEN 1 END) AS won_deals,
    COUNT(CASE WHEN sp.deal_stage IN ('Won', 'Lost') THEN 1 END) AS closed_deals,
    CAST(COUNT(CASE WHEN sp.deal_stage = 'Won' THEN 1 END) * 100.0
        /
        NULLIF(COUNT(CASE WHEN sp.deal_stage IN ('Won', 'Lost') THEN 1 END), 0
        )
        AS DECIMAL(5,2)
    ) AS win_rate_percentage
FROM vw_sales_pipeline AS sp
JOIN vw_sales_teams AS st
    ON sp.sales_agent = st.sales_agent
GROUP BY st.manager
ORDER BY win_rate_percentage DESC;


-- 4. For the product GTX Plus Pro, find which regional office sold the most units.
PRINT '--- Objective 2.4: GTX Plus Pro Units Sold by Regional Office ---';
SELECT
    st.regional_office,
    COUNT(*) AS units_sold
FROM vw_sales_pipeline sp
INNER JOIN vw_sales_teams st
    ON sp.sales_agent = st.sales_agent
WHERE sp.product = 'GTX Plus Pro'
    AND sp.deal_stage = 'Won'
GROUP BY st.regional_office
ORDER BY units_sold DESC;


-- ==================================================================================
-- OBJECTIVE 3: PRODUCT ANALYSIS
-- ==================================================================================

-- 1. For March deals, identify the top product by revenue and compare it to the top by units sold.
PRINT '--- Objective 3.1: March Deals - Revenue vs Units Sold by Product ---';
SELECT
    product,
    SUM(close_value) AS total_revenue,
    COUNT(*) AS units_sold
FROM vw_sales_pipeline
WHERE MONTH(close_date) = 3
    AND deal_stage = 'Won'
GROUP BY product
ORDER BY total_revenue DESC;


-- 2. Calculate the average difference between "sales_price" and "close_value" for each product, 
-- and note if the results suggest a data issue.
PRINT '--- Objective 3.2: Price Variance and Potential Data Issues ---';
SELECT 
    p.product,
    AVG(pr.sales_price) AS standard_sales_price,
    AVG(p.close_value) AS avg_close_value,
    AVG(pr.sales_price - p.close_value) AS avg_price_difference,
    AVG((pr.sales_price - p.close_value) / NULLIF(pr.sales_price, 0)) * 100.0 AS avg_discount_percentage
FROM vw_sales_pipeline p
JOIN vw_products pr ON p.product = pr.product
WHERE p.deal_stage = 'Won'
GROUP BY p.product;

/*
product	standard_sales_price	avg_close_value	avg_price_difference	avg_discount_percentage
GTX Plus Pro	5482.000000	5489.876826	-7.876826	-0.143685274030248
MG Special	55.000000	55.192938	-0.192938	-0.350796744239367
GTX Basic	550.000000	545.642622	4.357377	0.792250372578241
GTK 500	26768.000000	26707.466666	60.533333	0.226140665471209
MG Advanced	3393.000000	3388.970948	4.029051	0.118746006123418
GTX Plus Basic	1096.000000	1080.053598	15.946401	1.454963615430187
*/

-- 3. Calculate total revenue by product series and compare their performance.
PRINT '--- Objective 3.3: Total Revenue by Product Series ---';
SELECT 
    pr.series,
    SUM(p.close_value) AS total_revenue,
    COUNT(p.opportunity_id) AS total_deals_won
FROM vw_sales_pipeline p
JOIN vw_products pr ON p.product = pr.product
WHERE p.deal_stage = 'Won'
GROUP BY pr.series
ORDER BY total_revenue DESC;


-- ==================================================================================
-- OBJECTIVE 4: ACCOUNT ANALYSIS
-- ==================================================================================

-- 1. Calculate revenue by office location, and identify the lowest performer.
PRINT '--- Objective 4.1: Revenue by Client Office Location ---';
SELECT 
    a.office_location,
    SUM(p.close_value) AS total_revenue
FROM vw_sales_pipeline p
JOIN vw_accounts a ON p.account = a.account
WHERE p.deal_stage = 'Won'
GROUP BY a.office_location
ORDER BY total_revenue ASC;


-- 2. Find the gap in years between the oldest and newest customer, and name those companies.
PRINT '--- Objective 4.2: Customer Age Span and Extreme Companies ---';
WITH AgeBounds AS (
    SELECT 
        MIN(year_established) AS oldest_year,
        MAX(year_established) AS newest_year,
        MAX(year_established) - MIN(year_established) AS year_gap
    FROM vw_accounts
)
SELECT 
    (SELECT year_gap FROM AgeBounds) AS year_gap,
    a.account AS company_name,
    a.year_established,
    CASE 
        WHEN a.year_established = (SELECT oldest_year FROM AgeBounds) THEN 'Oldest Customer'
        WHEN a.year_established = (SELECT newest_year FROM AgeBounds) THEN 'Newest Customer'
    END AS customer_status
FROM vw_accounts a
WHERE a.year_established = (SELECT oldest_year FROM AgeBounds)
   OR a.year_established = (SELECT newest_year FROM AgeBounds);


-- 3. Which accounts that were subsidiaries had the most lost sales opportunities?
PRINT '--- Objective 4.3: Lost Opportunities for Subsidiary Accounts ---';
SELECT 
    p.account AS subsidiary_account,
    a.subsidiary_of AS parent_company,
    COUNT(*) AS lost_deals_count
FROM vw_sales_pipeline p
JOIN vw_accounts a ON p.account = a.account
WHERE a.subsidiary_of IS NOT NULL AND p.deal_stage = 'Lost'
GROUP BY p.account, a.subsidiary_of
ORDER BY lost_deals_count DESC;


-- 4. Join the companies to their subsidiaries. Which parent group had the highest total company revenue?
PRINT '--- Objective 4.4: Parent-Subsidiary Structure and Corporate Revenue ---';
SELECT 
    p.account AS parent_company,
    p.revenue AS parent_annual_revenue,
    SUM(s.revenue) AS combined_subsidiaries_annual_revenue,
    (p.revenue + SUM(s.revenue)) AS total_corporate_group_revenue
FROM vw_accounts p
JOIN vw_accounts s ON s.subsidiary_of = p.account
GROUP BY p.account, p.revenue
ORDER BY total_corporate_group_revenue DESC;


-- ==================================================================================
-- FINAL STEP: FINAL PROJECT QUESTION
-- ==================================================================================

-- Question: What is the total revenue of Acme Corp and all of its subsidiaries?
PRINT '--- Final Step: Acme Corp & Subsidiaries Revenue Analysis ---';

-- Interpretation A: Sum of Company Annual Revenue (from Firmographic Accounts Table in Millions USD)
SELECT 
    'Annual Corporate Revenue (Millions USD)' AS metric_type,
    SUM(revenue) AS total_value
FROM vw_accounts
WHERE account = 'Acme Corp' OR subsidiary_of = 'Acme Corp';

-- Interpretation B: Sum of Won Sales Values from the Pipeline (CRM Performance in USD)
SELECT 
    'Won Pipeline Sales Revenue (USD)' AS metric_type,
    SUM(p.close_value) AS total_value
FROM vw_sales_pipeline p
JOIN vw_accounts a ON p.account = a.account
WHERE (a.account = 'Acme Corp' OR a.subsidiary_of = 'Acme Corp') 
  AND p.deal_stage = 'Won';